var N = null;var sourcesIndex = {};
sourcesIndex["avmath"] = {"name":"","dirs":[{"name":"isa","files":["atmosphere.rs","mod.rs"]}],"files":["calculations.rs","constants.rs","lib.rs","si.rs"]};
sourcesIndex["gauge_sys"] = {"name":"","files":["ffi.rs","lib.rs","types.rs"]};
sourcesIndex["simconnect_sys"] = {"name":"","files":["ffi.rs","lib.rs","simconnect.rs"]};
sourcesIndex["wt_cj4"] = {"name":"","files":["control_params.rs","engines.rs","fadec.rs","lib.rs","state.rs"]};
sourcesIndex["wt_cj4_wasm"] = {"name":"","files":["gauges.rs","interop.rs","lib.rs"]};
sourcesIndex["wt_flight_recorder"] = {"name":"","files":["flight_data_recorder.rs","lib.rs"]};
sourcesIndex["wt_flight_to_csv"] = {"name":"","files":["main.rs"]};
sourcesIndex["wt_systems"] = {"name":"","files":["lib.rs","pid.rs","testing.rs"]};
createSourceSidebar();
