[package]
name = "avmath"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
uom = { version = "0.30.0" }
serde = { version = "1", features = ["derive"], optional = true }
